# =========================================
# CONFIGURAÇÃO DO BANCO DE DADOS
# =========================================

# URL de conexão com o PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/medicontrol

# Usuário do PostgreSQL
spring.datasource.username=postgres

# Senha do PostgreSQL
spring.datasource.password=Gt@122838

# Driver do PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# =========================================
# CONFIGURAÇÕES JPA / HIBERNATE
# =========================================

# Atualiza automaticamente as tabelas
spring.jpa.hibernate.ddl-auto=update

# Mostra os comandos SQL no terminal
spring.jpa.show-sql=true

# Formata o SQL exibido
spring.jpa.properties.hibernate.format_sql=true