# Nome da aplicação
spring.application.name=medicontrol

# Configuração do PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/medicontrol
spring.datasource.username=postgres
spring.datasource.password=postgres123

# Driver PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuração JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update

# Mostrar SQL no terminal
spring.jpa.show-sql=true

# Dialeto PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
